export const dataMascotas = [
  {
    id: 0,
    titulo: " XIHUAN Impiador Pata Perro, Limpiador De Patas De Perros",
    producto:
      "XIHUAN Impiador Pata Perro, Limpiador De Patas De Perros, Portátil Desmontable Limpiador De Huellas De Perro, Limpiador Patas Perro Mascota para Limpiar Los Pies Sucios De Mascotas",
    info: " El limpiador de patas de perro XIHUAN es un dispositivo portátil y desmontable diseñado para limpiar las patas sucias de tu mascota. Está hecho de material de silicona suave y duradero, con pelos de silicona en el interior que son cómodos para limpiar y eliminar la suciedad sin dañar las patas de tu perro. Este limpiador de patas es fácil de usar: se llena con agua y un poco de jabón para perros, se colocan las patas del perro dentro y se gira para limpiar eficazmente. Además, es desmontable, lo que facilita su limpieza y mantenimiento.",
    img: "https://m.media-amazon.com/images/I/61+vyup4k4L._AC_SX679_.jpg",
    linkAfiliado: "https://amzn.to/3oBvQZ9",
    review:
      "Review del producto: El limpiador de patas de perro XIHUAN ha recibido una calificación de 4.0 sobre 5 estrellas, basado en 137 valoraciones. Los usuarios destacan el material suave y duradero de silicona, que no daña las patas de las mascotas. También aprecian su facilidad de uso y limpieza, así como su portabilidad. Sin embargo, algunos usuarios han mencionado que el tamaño del limpiador puede ser un poco pequeño para perros de mayor tamaño. Material de silicona suave y duradero: Proporciona una limpieza cómoda y efectiva de las patas de tu mascota sin dañar su piel.Fácil de usar y desmontar: Solo necesitas llenarlo con agua y jabón, y girarlo para limpiar las patas sucias. Además, se puede desmontar fácilmente para su limpieza. Portátil y práctico: Su diseño compacto y ligero permite llevarlo contigo a cualquier lugar para mantener las patas de tu perro limpias en todo momento.",
    pro: "Material de silicona suave y duradero. Fácil de usar y desmontar para su limpieza. Portátil y práctico para usar en cualquier lugar.",
    contra: "Puede ser un poco pequeño para perros de mayor tamaño.",
    resumen:
      "En resumen, el limpiador de patas de perro XIHUAN es una solución conveniente para mantener las patas de tu mascota limpias y libres de suciedad. Con su material suave, facilidad de uso y portabilidad, proporciona una forma eficaz de mantener la higiene de tu perro. Sin embargo, es importante considerar el tamaño del limpiador según el tamaño de tu perro para asegurarte de que sea adecuado.",
  },
  {
    id: 1,
    titulo: " Bonve Pet Cortapelo para Perros y Gatos",
    producto: "Bonve Pet Cortapelo para Perros y Gatos, Cortapelo para Perros Gatos Mascotas Profesional, Bajo Ruido Menos de 50db, con 11 Accesorios, Cargador, Base de Carga",
    info: "El Bonve Pet Cortapelo para Perros y Gatos es una herramienta de calidad profesional diseñada para cortar el pelo de manera segura y eficiente en mascotas. Viene con 11 accesorios, incluyendo peines de diferentes longitudes, tijeras y un cepillo de limpieza. El cortapelo está hecho de acero inoxidable y cerámica, lo que garantiza durabilidad y precisión en el corte. Además, cuenta con 5 posiciones ajustables para adaptarse a diferentes tipos de pelo.",
    img: "https://m.media-amazon.com/images/I/71hY5avsG2L._AC_SY355_.jpg",
    linkAfiliado: "https://amzn.to/3WBmqcS",
    review: "El Bonve Pet Cortapelo ha recibido una calificación promedio de 4.2 de 5 estrellas en base a más de 5,300 valoraciones. Los usuarios destacan su potencia y eficiencia para cortar el pelo de sus mascotas, así como su bajo nivel de ruido, lo que evita que las mascotas se pongan nerviosas durante el proceso. También mencionan la facilidad de uso y la comodidad del diseño ergonómico. Versatilidad: Con los diferentes accesorios incluidos, puedes adaptar el corte según la longitud deseada, lo que te permite realizar diferentes estilos de peinado para tus mascotas. Calidad profesional: El cortapelo está hecho con materiales de alta calidad que garantizan un corte preciso y duradero. No tendrás que preocuparte por reemplazarlo con frecuencia. Fácil de usar y seguro: Gracias a su diseño ergonómico y las cuchillas desmontables, el Bonve Pet Cortapelo es fácil de manejar y limpiar. Además, las cuchillas de cerámica y titanio protegen a las mascotas de posibles lesiones. Bajo nivel de ruido: El cortapelo funciona silenciosamente, lo que ayuda a mantener a las mascotas tranquilas y cómodas durante el proceso de corte. Excelente relación calidad-precio: Este cortapelo ofrece un rendimiento profesional a un precio asequible, lo que lo convierte en una opción atractiva para aquellos que desean cuidar el pelo de sus mascotas en casa.",
    pro: "Viene con múltiples accesorios para adaptarse a diferentes necesidades de corte. Cuchillas de alta calidad que garantizan un corte preciso. Bajo nivel de ruido que evita el estrés en las mascotas. Fácil de usar y limpiar. Buena relación calidad-precio.",
    contra: "Algunos usuarios mencionan que la duración de la batería podría ser mejor.",
    resumen: "En general, el Bonve Pet Cortapelo para Perros y Gatos es una excelente opción para aquellos que desean realizar el corte de pelo de sus mascotas en casa. Ofrece calidad, versatilidad y comodidad a un precio asequible.",
  },
  {
    id: 2,
    titulo: "BIGWING Style-Parque Perro Gato Conejo Mascota de Juego Entrenamiento ",
    producto: "BIGWING Style-Parque Perro Gato Conejo Mascota de Juego Entrenamiento Dormitorio Plegable Lavable Durable Octágono 125x125x58 CM, Azul",
    info: "El BIGWING Style-Parque Perro Gato Conejo Mascota es un parque de juego y entrenamiento para mascotas diseñado para proporcionar un espacio cómodo y seguro. Tiene forma de octágono y está fabricado con material de poliuretano duradero. Con dimensiones de 125 cm de largo, 125 cm de ancho y 58 cm de altura, es lo suficientemente grande para acomodar a varias mascotas al mismo tiempo. Cuenta con una puerta lateral y un techo de tela tipo red que se puede abrir parcial o completamente.",
    img: "https://m.media-amazon.com/images/I/819dVzLOMoL._AC_SX679_.jpg",
    linkAfiliado: "BIGWING Style-Parque Perro Gato Conejo Mascota de Juego Entrenamiento Dormitorio Plegable Lavable Durable Octágono 125x 125x 58 CM, Azúl",
    review: "El BIGWING Style-Parque Perro Gato Conejo Mascota ha recibido una calificación promedio de 4.1 de 5 estrellas en base a más de 6,100 valoraciones. Los usuarios elogian su diseño exclusivo y su comodidad para las mascotas. También destacan la facilidad de montaje y desmontaje, así como la estabilidad y durabilidad de la estructura de acero. Espacio amplio y seguro: Con dimensiones generosas, este parque proporciona un espacio cómodo y seguro para que tus mascotas jueguen, se relajen y realicen entrenamientos. Diseño práctico: La puerta lateral facilita el acceso de las mascotas al parque, y el techo de tela tipo red permite una buena ventilación y visibilidad. Durabilidad y estabilidad: Fabricado con material de poliuretano resistente y una estructura de acero, este parque es duradero y estable, brindando tranquilidad y seguridad para tus mascotas. Fácil montaje y portabilidad: Se puede montar y desmontar de manera sencilla, lo que facilita su transporte y almacenamiento cuando no esté en uso. Servicio postventa: El fabricante ofrece servicio de intercambio o devolución dentro de los 12 meses, así como un servicio posventa permanente.",
    pro: "Amplio espacio para varias mascotas. Diseño exclusivo y práctico con puerta lateral y techo de tela tipo red. Construcción duradera con material de poliuretano y estructura de acero. Fácil montaje y desmontaje. Portátil y fácil de almacenar.",
    contra: "Algunos usuarios mencionan que las costuras podrían ser más resistentes.",
    resumen: "En resumen, el BIGWING Style-Parque Perro Gato Conejo Mascota es una excelente opción para brindar un espacio seguro y cómodo a tus mascotas. Con su diseño práctico, durabilidad y facilidad de uso, este parque ofrece una solución conveniente para el juego, entrenamiento y descanso de tus mascotas.",
  },
  {
    id: 3,
    titulo: "JOFLVA Dispensador De Agua para Mascotas,",
    producto: "JOFLVA Dispensador De Agua para Mascotas, Bebedero Perro, Bebedero Gatos, Bebederos Perros Pequeño Y Mediano Automaticos, Bebedero para Mascotas 2.5L Dispensador De Agua Automático para Perros Gatos.",
    info: "l JOFLVA Dispensador De Agua para Mascotas es un bebedero automático diseñado para perros y gatos. Tiene una capacidad de 2.5 litros, lo que significa que no necesitarás rellenarlo con frecuencia, y puede satisfacer las necesidades de agua de perros pequeños o gatos grandes durante 7 a 15 días. Está hecho de material plástico de calidad alimentaria, que es seguro, resistente y duradero. El dispensador utiliza la gravedad para asegurar un suministro continuo de agua fresca sin consumo de energía.",
    img: "https://m.media-amazon.com/images/I/61dqfJ3nbAL._AC_SX425_.jpg",
    linkAfiliado: "https://amzn.to/3MZB2zK",
    review: "El JOFLVA Dispensador De Agua para Mascotas ha recibido una calificación promedio de 4.5 de 5 estrellas en base a 100 valoraciones. Los usuarios destacan su gran capacidad y la conveniencia de no tener que preocuparse por rellenar el agua con frecuencia. También elogian la calidad del material y su diseño desmontable, que facilita la limpieza y reduce los residuos bacterianos. Además, el hecho de que no requiera electricidad lo hace seguro y silencioso. Gran capacidad: Con una capacidad de 2.5 litros, este dispensador de agua puede satisfacer las necesidades de agua de tus mascotas durante varios días, lo que es especialmente útil si estás ausente por períodos prolongados o si tienes varias mascotas. Material seguro y duradero: Fabricado con material plástico de calidad alimentaria, este bebedero es seguro y resistente. No tiene olores peculiares y mantiene el agua de tus mascotas limpia, saludable y segura. Funcionamiento sin consumo de energía: El dispensador utiliza la gravedad para suministrar agua de forma continua, eliminando la necesidad de pilas o electricidad. Es una opción segura y silenciosa para tus mascotas. Fácil de usar y limpiar: El diseño desmontable del dispensador permite una fácil limpieza y reducción de los residuos bacterianos. Viene con un cepillo de limpieza de filtro de agua para mayor comodidad. Servicio postventa: El fabricante se compromete a proporcionar productos y servicios satisfactorios a los clientes, ofreciendo una garantía de satisfacción y soluciones adecuadas en caso de problemas.",
    pro: "Gran capacidad para satisfacer las necesidades de agua de las mascotas durante varios días. Material seguro de calidad alimentaria y diseño desmontable para una limpieza fácil. Funcionamiento sin consumo de energía, seguro y silencioso. Fácil de usar y mantener. Servicio postventa satisfactorio.",
    contra: "Algunos usuarios mencionan que el flujo de agua puede ser lento en ocasiones.",
    resumen: "En resumen, el JOFLVA Dispensador De Agua para Mascotas es una excelente opción para mantener a tus mascotas hidratadas de manera conveniente y segura. Su capacidad, material seguro, funcionamiento sin energía y facilidad de uso y limpieza lo convierten en una opción práctica para los dueños de mascotas que desean garantizar un suministro continuo de agua fresca.",
  },
  {
    id: 4,
    titulo: "Masthome Escaleras para Perros de 4 Escalones",
    producto: "Masthome Escaleras para Perros de 4 Escalones, Escaleras de Esponja para Mascotas con Funda de Tela Extraíble y Lavable, para Camas de Alta y Sofá, Apto para Mascotas de Menos de 23 kg - Marrón",
    info: "Las escaleras para perros de Masthome son un accesorio perfecto para ayudar a tus pequeñas mascotas a alcanzar camas altas o sofás cómodamente. Están fabricadas con materiales de calidad y son fáciles de limpiar. La capa exterior está hecha de gamuza suave, impermeable y antisuciedad, que se puede quitar fácilmente y lavar a mano o en la lavadora, manteniendo las escaleras limpias y en buen estado. La capa interior está hecha de esponja elástica de alta calidad que ofrece un rebote alto y no se deforma fácilmente.",
    img: "https://m.media-amazon.com/images/I/81tSJoXd0DL._AC_SX679_.jpg",
    linkAfiliado: "https://amzn.to/45vaBsC",
    review: "Las escaleras para perros de Masthome han recibido una calificación promedio de 4.3 de 5 estrellas en base a 117 valoraciones. Los usuarios destacan la calidad del material y la facilidad de limpieza de las escaleras. También mencionan que son muy resistentes gracias al fondo antideslizante, y que los peldaños ofrecen una excelente tracción para que sus mascotas puedan subir y bajar cómodamente. Además, el diseño ligero y portátil permite mover las escaleras fácilmente por la casa o llevarlas de viaje. Ayuda a tus mascotas: Estas escaleras son ideales para ayudar a tus perros pequeños, gatos o cachorros a alcanzar camas o sofás altos sin esfuerzo, evitando saltos bruscos que puedan ser perjudiciales para sus articulaciones. Material de calidad y fácil de limpiar: La capa exterior de gamuza suave es resistente al agua y a la suciedad. Se puede quitar fácilmente para su lavado a mano o en la lavadora, lo que facilita el mantenimiento y la higiene de las escaleras. Seguras y resistentes: Las escaleras cuentan con un fondo antideslizante que proporciona estabilidad y resistencia, asegurando que tus mascotas puedan subir y bajar de manera segura. Los peldaños ofrecen una excelente tracción. Ligera y portátil: Estas escaleras son sorprendentemente ligeras pero muy robustas, lo que las hace fáciles de mover por la casa según sea necesario. También son prácticas para llevar en viajes al aire libre.",
    pro: "Ayuda a prevenir lesiones: Estas escaleras proporcionan una forma segura y conveniente para que tus mascotas suban y bajen de camas o sofás altos sin tener que saltar, lo que puede ayudar a prevenir lesiones en sus articulaciones, especialmente en mascotas pequeñas o en aquellas con problemas de movilidad.",
    contra: "Algunos usuarios mencionan que las escaleras pueden tardar un tiempo en recuperar su forma original después de desempacarlas debido al embalaje de compresión al vacío.",
    resumen: "En resumen, las escaleras para perros de Masthome son una opción conveniente y segura para ayudar a tus mascotas a alcanzar camas o sofás altos. Su material de calidad, facilidad de limpieza, resistencia y portabilidad las convierten en una opción práctica para aquellos que desean brindar comodidad y accesibilidad a sus mascotas.",
  },
];

/***{
    id: "",
    titulo: "",
    producto: "",
    info: "",
    img: "",
    linkAfiliado: "",
    review: "",
    pro: "",
    contra: "",
    resumen: "",
  }, */
