export const dataInformatica = [
  {
    id: 0,
    titulo: "Chromecast con Google TV (HD)",
    producto:
      "Chromecast con Google TV (HD) - Reproduce contenido en streaming en el televisor con el mando de control por voz",
    info: "El Chromecast con Google TV es un dispositivo que te permite reproducir contenido en streaming en tu televisor de forma sencilla y con alta calidad de imagen. Viene con un mando de control por voz que facilita la navegación y búsqueda de películas y series. La pantalla de inicio del Chromecast muestra todas tus opciones de entretenimiento en un solo lugar, brindándote acceso a servicios de streaming populares. También ofrece sugerencias personalizadas basadas en tus suscripciones, hábitos de visualización y contenido adquirido. Además, puedes crear perfiles infantiles con controles parentales y utilizar el Asistente de Google para realizar búsquedas por voz, reproducir música y obtener respuestas.",
    img: "https://m.media-amazon.com/images/I/51qIuxdWalL._AC_SL1500_.jpg",
    linkAfiliado: "https://amzn.to/45qlv36",
    review:
      "El Chromecast con Google TV ha recibido una calificación promedio de 4.7 de 5 estrellas con más de 5,923 valoraciones. Los usuarios han elogiado su facilidad de uso y la calidad de imagen en alta definición. El mando de control por voz ha sido destacado como una característica conveniente que agiliza la navegación y búsqueda de contenido. Los usuarios también aprecian la función de sugerencias personalizadas, ya que les permite descubrir nuevo contenido según sus preferencias. La capacidad de crear perfiles infantiles y configurar controles parentales también ha sido valorada positivamente Experiencia de entretenimiento mejorada: El Chromecast con Google TV te permite disfrutar de películas y series en streaming en tu televisor, brindándote acceso a una amplia variedad de servicios de entretenimiento en un solo dispositivo Control por voz: El mando de control por voz facilita la búsqueda de contenido y la navegación, permitiéndote encontrar rápidamente lo que deseas ver. Sugerencias personalizadas: El Chromecast ofrece recomendaciones basadas en tus preferencias y hábitos de visualización, lo que te ayuda a descubrir contenido nuevo y emocionante Controles parentales: Con la función de perfiles infantiles y controles parentales, puedes configurar límites de uso y garantizar un entorno seguro para los más pequeños de la familia, Integración con el Asistente de Google Puedes utilizar el Asistente de Google para realizar búsquedas por voz, reproducir música y obtener respuestas a tus preguntas directamente desde el mando a distancia.",
    pro: "Fácil de usar y configurar, Calidad de imagen en alta definición, Mando de control por voz para una navegación conveniente.   Sugerencias personalizadas basadas en tus preferencias.  Controles parentales para un entorno seguro.",
    contra:
      "Requiere una conexión Wi-Fi estable para transmitir contenido, La disponibilidad de servicios de streaming puede variar según la región.",
    resumen:
      " En resumen, el Chromecast con Google TV es un dispositivo versátil que mejora tu experiencia de entretenimiento en el televisor. Con su mando de control por voz, sugerencias personalizadas y controles parentales, ofrece una manera conveniente y segura de disfrutar de películas y series en alta definición.",
  },
  {
    id: 1,
    titulo: "Cámara IP WiFi 360° Cámara de Vigilancia ",
    producto:
      "TP-Link TAPO C200 - Cámara IP WiFi 360° Cámara de Vigilancia FHD 1080p,Visión nocturna",
    info: "La TP-Link TAPO C200 es una cámara de vigilancia IP WiFi que ofrece una calidad de imagen Full HD 1080p y una visión nocturna avanzada. Con su capacidad de giro e inclinación de 360° y 114° respectivamente, la cámara brinda una amplia cobertura para capturar cada momento. La detección de movimiento activa notificaciones instantáneas a través de la aplicación Tapo, y puede activar efectos de luz y sonido para disuadir a visitantes no deseados. Además, cuenta con audio bidireccional, lo que te permite comunicarte de forma remota y tener conversaciones claras con tu bebé o mascota. La cámara admite almacenamiento local en una tarjeta microSD (hasta 128 GB) o en la nube con una prueba gratuita de 30 días.",
    img: "https://m.media-amazon.com/images/I/61BWTcWOFSL._AC_SX679_.jpg",
    linkAfiliado: "https://amzn.to/3q1UeDU",
    review:
      "La TP-Link TAPO C200 ha recibido una calificación promedio de 4.6 de 5 estrellas con más de 87,320 valoraciones. Los usuarios han elogiado la calidad de imagen nítida y la facilidad de instalación. La capacidad de controlar la cámara de forma remota a través de la aplicación Tapo y la compatibilidad con asistentes de voz como Alexa y Google Assistant también han sido destacadas. La función de detección de movimiento y las notificaciones instantáneas han sido valoradas positivamente por brindar una mayor seguridad en el hogar. Además, los usuarios han apreciado el modo de privacidad, que les permite cerrar físicamente la lente de la cámara para garantizar la seguridad de la privacidad. Calidad de imagen Full HD <br> La TP-Link TAPO C200 ofrece una alta definición de imagen, lo que te permite ver con claridad los detalles en tus grabaciones de video. Amplia cobertura de vigilancia: Con su capacidad de giro e inclinación de 360° y 114°, la cámara puede cubrir un gran área y capturar cada momento importante. Detección de movimiento y notificaciones instantáneas: Recibirás alertas en tu teléfono cuando se detecte movimiento, lo que te permite tomar acciones rápidas si es necesario. Visión nocturna avanzada: La cámara cuenta con visión nocturna que te permite monitorear tu hogar incluso en condiciones de poca luz, con una distancia visual de hasta 10 metros. Audio bidireccional: Puedes comunicarte de forma remota a través de la cámara utilizando el micrófono y el altavoz incorporados, lo que facilita la interacción con tu familia o mascotas. Almacenamiento flexible: La cámara admite almacenamiento local en una tarjeta microSD de hasta 128 GB o en la nube con una prueba gratuita de 30 días, lo que te brinda opciones para acceder a tus grabaciones en cualquier momento.",
    pro: "Calidad de imagen Full HD 1080p.Amplia cobertura de vigilancia con giro e inclinación de 360° y 114°. Detección de movimiento con notificaciones instantáneas. Visión nocturna avanzada para vigilancia en condiciones de poca luz. Audio bidireccional para comunicación remota. Modo de privacidad para garantizar la seguridad de la privacidad. Almacenamiento flexible en tarjeta microSD o en la nube.",
    contra:
      "Requiere una conexión WiFi estable para funcionar correctamente. La tarjeta microSD para almacenamiento local no está incluida.",
    resumen:
      "En resumen, la TP-Link TAPO C200 es una cámara de vigilancia WiFi que ofrece una alta calidad de imagen, visión nocturna, detección de movimiento y audio bidireccional. Con su capacidad de giro e inclinación, brinda una amplia cobertura de vigilancia. Además, cuenta con opciones flexibles de almacenamiento y un modo de privacidad para garantizar la seguridad de la privacidad.",
  },
  {
    id: 2,
    titulo: "Echo Dot (5.ª generación, modelo de 2022)",
    producto:
      "Echo Dot (5.ª generación, modelo de 2022) | Altavoz inteligente Bluetooth con Alexa | Antracita",
    info: "El Echo Dot de 5ª generación es un altavoz inteligente Bluetooth con Alexa, diseñado por Amazon. Cuenta con un sonido mejorado en comparación con modelos anteriores, ofreciendo una calidad de audio potente, con voces más nítidas y graves intensos. Puedes controlar tu música y contenido favoritos, reproducir música, audiolibros y podcasts de servicios de música en streaming como Amazon Music, Apple Music, Spotify, Deezer, entre otros, o usar la conexión Bluetooth integrada para transmitir contenido desde tus dispositivos.Con la ayuda de Alexa, siempre tendrás un asistente a tu disposición. Puedes pedirle información sobre el clima, establecer temporizadores, hacer preguntas o incluso disfrutar de un chiste. Además, puedes configurar alarmas y posponerlas con un simple toque.",
    img: "https://m.media-amazon.com/images/I/71C3lbbeLsL._AC_SX679_.jpg",
    linkAfiliado: "https://amzn.to/3q2vJq0",
    review:
      "El Echo Dot (5.ª generación) ha recibido una calificación promedio de 4.6 de 5 estrellas con más de 6,725 valoraciones. Los usuarios han elogiado la mejora en la calidad de sonido en comparación con modelos anteriores, así como la facilidad de uso y la integración con Alexa. También han destacado la capacidad de controlar dispositivos inteligentes y crear rutinas automatizadas. La función de vinculación con otros dispositivos Echo ha sido valorada positivamente por la posibilidad de crear un sistema de sonido envolvente en el hogar. Además, la preocupación por la sostenibilidad y los materiales reciclados ha sido bien recibida por los usuarios.Mejora en la calidad de sonido: Disfruta de un audio potente con voces nítidas y graves intensos. Control de música y contenido: Accede a una amplia variedad de servicios de música en streaming o utiliza la conexión Bluetooth para transmitir contenido desde tus dispositivos.; Asistente de voz Alexa: Obtén respuestas a tus preguntas, establece temporizadores, configura alarmas y más con solo usar tu voz. Control de dispositivos inteligentes: Compatible con una variedad de dispositivos de hogar digital, permitiéndote controlar luces, termostatos, y otros dispositivos mediante comandos de voz. Vinculación con otros dispositivos Echo: Crea un sistema de sonido envolvente en tu hogar al vincular varios dispositivos Echo compatibles. Diseño sostenible: El Echo Dot tiene certificación Climate Pledge Friendly, lo que garantiza que se ha tenido en cuenta la sostenibilidad en su fabricación.",
    pro: "Mejora en la calidad de sonido. Integración completa con el asistente de voz Alexa. Control de dispositivos inteligentes y creación de rutinas automatizadas. Posibilidad de vinculación con otros dispositivos Echo. Enfoque en la sostenibilidad y el uso de materiales reciclados.",
    contra:
      "Algunos usuarios han informado de problemas de conectividad Bluetooth en ciertos casos. La calidad del sonido puede no ser comparable a sistemas de altavoces más avanzados.",
    resumen:
      "En resumen, el Echo Dot (5.ª generación) es un altavoz inteligente Bluetooth con Alexa que ofrece una mejora en la calidad de sonido, control de música y contenido, integración con dispositivos inteligentes y un diseño sostenible. Es una opción recomendada para aquellos que deseen disfrutar de un sonido potente y nítido en cualquier habitación, al tiempo que se benefician de las funciones y la comodidad que ofrece Alexa.",
  },
  {
    id: 3,
    titulo: "GoPro HERO10 Black - Cámara de acción",
    producto: "GoPro HERO10 Black - Cámara de acción a prueba de agua con LCD frontal y pantallas traseras táctiles, video 5.3K60 Ultra HD, fotos de 23MP, transmisión en vivo de 1080p, cámara web, estabilización.",
    info: "La GoPro HERO10 Black es una cámara de acción de alta calidad diseñada para capturar momentos emocionantes y aventuras en alta resolución. Cuenta con un potente procesador GP2 que ofrece un rendimiento rápido y fluido, controles táctiles adaptables y el doble de velocidad de fotogramas para grabar contenido fluido. Con fotos de 23 MP y vídeos en resolución 5.3K a 60 fps, esta cámara permite capturar imágenes nítidas y vídeos con detalles precisos. Además, cuenta con estabilización HyperSmooth 4.0 para obtener vídeos suaves y alineados, incluso en condiciones de poca luz. Con conectividad rápida y fiable, puedes transferir fácilmente tus fotos y vídeos a tu teléfono o almacenarlos en la nube.",
    img: "https://m.media-amazon.com/images/I/51D1Rxpk0fL._AC_SY355_.jpg",
    linkAfiliado: "https://amzn.to/3OE02O0",
    review: "La GoPro HERO10 Black ha recibido muchas críticas positivas de los usuarios. Los usuarios elogian su rendimiento potente, la calidad de imagen óptima y la estabilización HyperSmooth mejorada. La capacidad de capturar fotos de alta resolución y vídeos en resolución 5.3K a 60 fps permite obtener resultados impresionantes y detallados. La función de cámara lenta 8x y la posibilidad de extraer fotogramas de alta calidad de los vídeos también son características apreciadas. Además, la conectividad rápida y la opción de almacenamiento en la nube facilitan la transferencia y el almacenamiento de los contenidos. Alta calidad de imagen: La GoPro HERO10 Black ofrece fotos de 23 MP y vídeos en resolución 5.3K a 60 fps, lo que garantiza una calidad de imagen excepcional y detalles precisos. Estabilización HyperSmooth 4.0: La función de estabilización HyperSmooth mejorada proporciona vídeos suaves y alineados, incluso en condiciones de movimiento intenso. Conectividad rápida y fiable: La cámara permite transferir fotos y vídeos de forma sencilla y rápida a través de la aplicación Quik o mediante una conexión por cable. También ofrece almacenamiento ilimitado en la nube con subida automática. Resistente y a prueba de agua: La GoPro HERO10 Black es resistente y está diseñada para soportar condiciones extremas, incluyendo ser sumergida en agua.",
    pro: "Alta resolución de imagen y vídeos nítidos. Estabilización HyperSmooth 4.0 mejorada para vídeos suaves Conectividad rápida y almacenamiento en la nube Resistente y a prueba de agua para aventuras al aire libre.",
    contra: "Precio más alto en comparación con otras cámaras de acción en el mercado. Algunos usuarios han reportado problemas de calentamiento durante un uso prolongado.",
    resumen: "En resumen, la GoPro HERO10 Black es una cámara de acción de alta calidad con características avanzadas y un rendimiento potente. Ofrece imágenes y vídeos de alta resolución, estabilización mejorada y conectividad rápida. Si estás buscando una cámara de acción versátil y resistente para capturar tus aventuras al aire libre, la GoPro HERO10 Black es una opción a considerar.",
  },{
    id: 4,
    titulo: "DJI Mini 3 Pro (DJI RC) - Dron de cámara ligero",
    producto: "DJI Mini 3 Pro (DJI RC) - Dron de cámara ligero y plegable con video de 4K/60fps, foto de 48MP, tiempo de vuelo de 34 minutos, detección de obstáculos tridireccionales, ideal para fotografía aérea y redes sociales",
    info: "El DJI Mini 3 Pro es un dron de cámara ligero y plegable diseñado para capturar imágenes y videos de alta calidad. Con un peso inferior a 8.78 oz, no requiere registro en la mayoría de los países y regiones. Su diseño compacto y plegable lo hace portátil y fácil de transportar en cualquier aventura",
    img: "https://m.media-amazon.com/images/I/61Y1P6uIRFL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    linkAfiliado: "https://amzn.to/3MZcWoA",
    review: "El dron cuenta con una cámara avanzada que puede grabar video en 4K a 60 fps y capturar fotos de 48MP. Su sistema de cámara incorpora una doble apertura ISO nativa y una apertura de f/1.7 para obtener imágenes nítidas tanto de día como de noche. Además, el DJI Mini 3 Pro ofrece una función de toma vertical para fotos de retrato, ideal para redes sociales.Con un tiempo de vuelo de hasta 34 minutos, el dron te permite explorar y capturar más de tu entorno. También cuenta con detección de obstáculos tridireccional y APAS 4.0, lo que proporciona una mayor seguridad y evita colisiones durante el vuelo. El DJI Mini 3 Pro incluye el nuevo control remoto DJI RC, que viene con la aplicación DJI Fly preinstalada y una pantalla HD integrada de 5.5 pulgadas. La resistencia máxima de velocidad del viento es de 35.1 ft/s (nivel 5), lo que te permite volar con confianza incluso en condiciones de viento fuerte.Además, el dron ofrece una amplia gama de características inteligentes, como FocusTrack, True Vertical Shooting, MasterShots, Timelapse y QuickTransfer, que facilitan la creación y el intercambio de contenido sobre la marcha.",
    pro: "Diseño ligero y plegable, fácil de transportar. Calidad de imagen de alta resolución con video 4K/60fps y fotos de 48MP. Detección de obstáculos tridireccionales y APAS 4.0 para una mayor seguridad durante el vuelo. Tiempo de vuelo prolongado de hasta 34 minutos.  Control remoto con pantalla HD integrada de 5.5 pulgadas para una visualización clara.",
    contra: "Precio más alto en comparación con otros modelos de drones.  Algunas características avanzadas pueden requerir experiencia previa en el manejo de drones.",
    resumen: "En resumen, el DJI Mini 3 Pro es un dron de cámara de alta calidad, ligero y plegable, ideal para fotografía aérea y redes sociales. Con su capacidad para grabar video en 4K/60fps, capturar fotos de 48MP y ofrecer una amplia gama de características inteligentes, este dron proporciona una experiencia de vuelo y creación de contenido excepcionales. Si estás buscando un dron portátil con excelente calidad de imagen y características avanzadas, el DJI Mini 3 Pro es una excelente opción.",
  },{
    id: 5,
    titulo: " UBeesize - Trípode extensible de 51 pulgadas",
    producto: "UBeesize - Trípode extensible de 51 pulgadas con control remoto Bluetooth para iPhone y Android, aluminio resistente, ligero. 2.2 lbs",
    info: "El trípode UBeesize es un trípode extensible de 51 pulgadas diseñado para brindar estabilidad y versatilidad en tus fotografías y videos. Está fabricado con aluminio resistente pero ligero, lo que lo hace fácil de transportar y duradero. Este trípode viene en un combo todo en uno, que incluye un palo selfie, permitiéndote tomar selfies y fotos/videos con una excelente estabilidad mientras tienes las manos libres. Es perfecto para diversas situaciones, como selfies, fotos de grupo, viajes de aventura, vlogging, videos de YouTube, transmisiones en vivo y más.",
    img: "https://m.media-amazon.com/images/I/61xAjSS+7SL._AC_SX679_.jpg",
    linkAfiliado: "https://amzn.to/3oAncKC",
    review: "El trípode es extensible desde 17.5 pulgadas hasta 51 pulgadas, lo que te brinda más posibilidades para capturar diferentes ángulos y composiciones. Además, cuenta con una rotación de cuello de 180 grados y una rotación de cabeza de 360 grados, lo que te permite encontrar el mejor ángulo de disparo y tomar selfies más satisfactorias. El trípode viene con un obturador remoto inalámbrico que se conecta a través de Bluetooth. Este control remoto de tamaño de bolsillo te permite tomar selfies o fotos grupales fácilmente desde una distancia de hasta 30 pies, sin necesidad de descargar una aplicación adicional. Es ampliamente compatible, ya que cuenta con un soporte universal para teléfono que se adapta a la mayoría de los smartphones con o sin funda. También incluye un tornillo universal de 1/4 pulgadas, lo que lo hace compatible con cámaras digitales, DSLR, cámaras de acción, cámaras GoPro, cámaras web y videocámaras.",
    pro: "Diseño extensible y ajustable para capturar diferentes ángulos y composiciones.Obturador remoto inalámbrico para tomar selfies fácilmente.Soporte universal para teléfono que se adapta a la mayoría de los smartphones. Ligero y fácil de transportar.Versátil y adecuado para diversas situaciones de fotografía y video.",
    contra: "El envío internacional puede tener un costo adicional. Algunos usuarios pueden preferir un trípode más robusto para usos profesionales.",
    resumen: "En resumen, el trípode UBeesize es una opción conveniente y versátil para aquellos que desean estabilidad y flexibilidad en sus fotografías y videos. Con su diseño extensible, control remoto inalámbrico y soporte universal para teléfono, este trípode es adecuado para una amplia gama de situaciones de captura de imágenes. Si buscas un trípode portátil y funcional para tus dispositivos móviles y cámaras, el UBeesize es una excelente opción.",
  },{
    id: 6,
    titulo: "VIZIO - Smart TV Full HD 1080p de 40 pulgadas con Apple AirPlay",
    producto: "VIZIO - Smart TV Full HD 1080p de 40 pulgadas con Apple AirPlay y Chromecast integrados, compatibilidad con Alexa, D40f-J09, modelo 2022",
    info: "El televisor inteligente VIZIO D40f-J09 es un televisor Full HD de 40 pulgadas con funciones inteligentes y una calidad de imagen clara y nítida. Está equipado con Apple AirPlay y Chromecast integrados, lo que te permite transmitir contenido desde tus dispositivos compatibles de forma inalámbrica.Con una resolución Full HD de 1080p, este televisor ofrece imágenes de alta definición con colores vibrantes y detalles nítidos. Cuenta con una luz de fondo LED de matriz completa, que distribuye uniformemente los LED en la pantalla para brindar una iluminación uniforme y un rendimiento de imagen superior.",
    img: "https://m.media-amazon.com/images/I/81YMd8mWQ+L._AC_SX466_.jpg",
    linkAfiliado: "https://amzn.to/3C0P7q0",
    review: "El televisor está impulsado por el procesador de imágenes IQ de VIZIO, que ofrece un procesamiento de imágenes superior, una navegación más rápida y tiempos de carga más rápidos para acceder rápidamente a tu contenido favorito. También cuenta con el V-Gaming Engine, que optimiza automáticamente el modo de imagen para juegos y ofrece una experiencia de juego más receptiva con características como el modo de juego automático, frecuencia de actualización variable con AMD FreeSync y bajo retraso de entrada. El televisor es compatible con Alexa, lo que te permite controlar el televisor con comandos de voz cuando se combina con un dispositivo Alexa. Puedes encender la televisión, cambiar de canal, ajustar el volumen y más usando comandos de voz.  Además, el televisor cuenta con la plataforma SmartCast de VIZIO, que ofrece una navegación intuitiva y acceso instantáneo a una amplia selección de aplicaciones de servicios de transmisión populares como Netflix, Disney+, YouTube, HBO Max y más. El paquete incluye un cable de alimentación, un mando a distancia y un soporte para el televisor.",
    pro: "Calidad de imagen clara y nítida con resolución Full HD 1080p. Apple AirPlay y Chromecast integrados para transmitir contenido desde dispositivos compatibles. Procesador de imágenes IQ para un procesamiento superior y tiempos de carga rápidos. V-Gaming Engine para una experiencia de juego optimizada. Compatibilidad con Alexa para control de voz convenientep Plataforma SmartCast para acceder a una amplia selección de aplicaciones de servicios de transmisión.",
    contra: "Algunos usuarios pueden preferir una resolución más alta, como 4K, para una experiencia de visualización más avanzada. La velocidad de actualización de 60 Hz puede no ser ideal para juegos con alta velocidad de fotogramas.",
    resumen: "En resumen, el VIZIO D40f-J09 es un televisor inteligente de 40 pulgadas que ofrece una calidad de imagen clara y funciones inteligentes para una experiencia de visualización satisfactoria. Con su compatibilidad con Apple AirPlay, Chromecast integrados y Alexa, así como su plataforma SmartCast, este televisor proporciona opciones de entretenimiento versátiles y un control conveniente. Si buscas un televisor Full HD con características inteligentes y un rendimiento sólido, el VIZIO D40f-J09 es una opción a considerar.",
  },
  
];
  
 
/***{
    id: "",
    titulo: "",
    producto: "",
    info: "",
    img: "",
    linkAfiliado: "",
    review: "",
    pro: "",
    contra: "",
    resumen: "",
  }, */