export const dataBelleza = [
 { id: 16,
  titulo: "NYX PROFESSIONAL MAKEUP Face Freezie - Imprimación refrescante + hidratante, maquillaje 10 en 1 para preparar el cuidado de la piel",
producto: "NYX PROFESSIONAL MAKEUP Face Freezie es una imprimación refrescante facial y crema hidratante en uno solo.",
  info: "Esta imprimación y crema hidratante facial 10 en 1 ofrece una sensación de enfriamiento y múltiples beneficios. Prepara la piel, la deja uniforme, suave, minimiza los poros, tensa, hidrata, esculpe y suaviza la piel.",
  img: "https://m.media-amazon.com/images/I/71GsuZi3MBL._SX466_.jpg",
  linkAfiliado: "https://amzn.to/3rQc7pV",
  review: "El producto ha sido calificado con 4.2 estrellas sobre 5, basado en 96 calificaciones. Los usuarios elogian su efecto refrescante y los múltiples beneficios que ofrece como imprimación y crema hidratante en uno solo.",
  pro: "Ventajas de NYX PROFESSIONAL MAKEUP Face Freezie:\n- Refrescante imprimación facial y crema hidratante en uno\n- Contiene hongo de nieve para hidratación\n- Niacinamida para apretar los poros\n- Sensación de enfriamiento\n- 10 beneficios en 1 producto",
  contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
  resumen: "En resumen, NYX PROFESSIONAL MAKEUP Face Freezie es una imprimación facial refrescante y crema hidratante que proporciona múltiples beneficios para la piel. Con hongo de nieve y niacinamida, ofrece hidratación y ayuda a apretar los poros. Los usuarios aprecian su efecto refrescante y versatilidad como imprimación y crema hidratante 10 en 1."
},{
    id: 15,
    titulo: "NYX MAQUILLAJE PROFESIONAL Brillo de mantequilla azúcar moreno - Paquete de 3 brillos de labios (Sugar High, Toffee, Butterscotch)",
    producto: "Los Brillos de Mantequilla de NYX MAQUILLAJE PROFESIONAL son suaves y sedosos, disponibles en una amplia variedad de tonos suntuosos.",
    info: "Estos brillos de mantequilla no son pegajosos y son perfectos para lograr labios besables. El paquete de 3 brillos incluye los tonos Sugar High, Toffee y Butterscotch, entre otros deliciosos tonos disponibles. Todos los productos de NYX MAQUILLAJE PROFESIONAL están certificados y reconocidos por PETA como libres de crueldad animal.",
    img: "https://m.media-amazon.com/images/I/61wTW1Z6knL._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3s0Hqi0",
    review: "El producto ha sido calificado con 4.5 estrellas sobre 5, basado en 95,694 calificaciones. Los usuarios elogian su textura suave y cremosa que no es pegajosa. Además, destacan la amplia variedad de tonos disponibles.",
    pro: "Textura suave y sedosa\n- Amplia variedad de tonos suntuosos\n- Cobertura transparente a media\n- No es pegajoso\n- Libre de crueldad animal",
    contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, los Brillos de Mantequilla de NYX MAQUILLAJE PROFESIONAL ofrecen una amplia gama de tonos suaves y sedosos que brindan una cobertura transparente a media. Su textura no pegajosa hace que los labios se sientan suaves y flexibles. Además, son productos libres de crueldad animal, certificados por PETA."
  }, {
    id: 14,
    titulo: "Physicians Formula Mineral Wear Diamond Metallic Liquid Sombra de ojos brillante bronce",
    producto: "La Physicians Formula Mineral Wear Diamond Metallic Liquid Sombra.",
    info: "Esta sombra de ojos líquida es parte de la colección Mineral Wear, que no contiene talco y es extra transpirable, ideal para personas con piel sensible. Además, ofrece protección UV adicional en algunos productos. Todo el maquillaje de Physicians Formula está formulado pensando en la salud y comodidad de la piel, utilizando ingredientes de alta calidad.",
    img: "https://m.media-amazon.com/images/I/81o1dCCpzdL._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3qkg2el",
    review: "La Physicians Formula Mineral Wear Diamond Metallic Liquid Sombra de ojos ha sido calificada con 4.4 estrellas sobre 5, basado en 193 calificaciones. Los usuarios elogian su prisma de colores metálicos y su efecto deslumbrante. También destacan que es ideal para pieles sensibles y que no ha sido probada en animales.",
    pro: "Efecto multicromático con colores metálicos\n- Contiene polvo de diamante real para un acabado de piedras preciosas\n- Enriquecida con agua mineral y vitamina E para el cuidado de la piel\n- Libre de crueldad animal",
    contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, la Physicians Formula Mineral Wear Diamond Metallic Liquid Sombra de ojos es una sombra líquida de colores metálicos que crea un efecto deslumbrante y arco iris en los ojos. Su fórmula enriquecida con polvo de diamante, agua mineral y vitamina E la hace ideal para pieles sensibles y amante de la piel. Además, es libre de crueldad animal y forma parte de la línea Mineral Wear que no contiene talco y ofrece protección UV adicional."
  },{
    id: 13,
    titulo: "Physicians Formula Polvo fijador de defensa natural",
    producto: "El Physicians Formula Polvo fijador de defensa natural es un palo de color.",
    info: "Este polvo fijador combina el complejo de defensa total de 360° para proteger contra los dañinos rayos solares (SPF), luz azul (RPF) y contaminación (PPF). Es ultra mezclable y ofrece una apariencia natural y sin esfuerzo.",
    img: "https://m.media-amazon.com/images/I/81g+a0lvEFL._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3KpeRkM",
    review: "El Physicians Formula Polvo fijador de defensa natural ha sido calificado con 4.2 estrellas sobre 5, basado en 968 calificaciones y 7 preguntas respondidas. Los usuarios destacan su fácil aplicación y la capacidad para añadir un toque de color de forma transparente en diferentes áreas del rostro. También elogian su capacidad para proteger la piel contra los daños del sol, luz azul y contaminación.",
    pro: "Fácil de usar y aplicar\n- Añade un toque de color transparente en ojos, labios y mejillas\n- Combate los signos del envejecimiento\n- Protege contra rayos solares, luz azul y contaminación\n- Adecuado para pieles sensibles",
    contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, el Physicians Formula Polvo fijador de defensa natural es una excelente opción para quienes buscan un maquillaje suave y protector para pieles sensibles. Su fórmula combina defensa total de 360° con un toque de color para proporcionar un aspecto natural y completo. Con una calificación positiva y elogios de los usuarios, este polvo fijador puede ser una opción ideal para aquellos que buscan una belleza saludable y protegida."
  },{
    id: 12,
    titulo: "REVLON PhotoReady Base sincera de acabado natural",
    producto: "La REVLON PhotoReady Base sincera de acabado natural es una base suave y cremosa que se aplica como una crema hidratante.",
    info: "Esta base no solo ofrece una apariencia natural, sino que también protege la piel con buenos ingredientes. Contiene propiedades anticontaminantes, antioxidantes y antiluz azul para proteger contra daños ambientales. Además, está fabricada sin aceites, parabenos, ftalatos, tintes sintéticos ni fragancias, lo que la hace adecuada para diferentes tipos de piel.",
    img: "https://m.media-amazon.com/images/I/71BgHO5tnIS._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3DIXNSP",
    review: "La REVLON PhotoReady Base sincera de acabado natural ha sido calificada con 4.4 estrellas sobre 5, basado en 7,639 calificaciones y 49 preguntas respondidas. Los usuarios elogian su sensación ligera y natural, así como la cobertura media que se puede construir según las necesidades. También valoran los ingredientes protectores y la amplia gama de tonos disponibles para adaptarse a diferentes tonos de piel.",
    pro: "Acabado natural y sensación ligera\n- Cobertura cómoda y construible\n- Protección contra daños ambientales, anticontaminación, antioxidante y antiluz azul\n- Libre de aceites, parabenos, ftalatos, tintes sintéticos y fragancias\n- Amplia variedad de tonos para diferentes tonos de piel",
    contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, la REVLON PhotoReady Base sincera de acabado natural es una opción versátil para aquellos que buscan una base suave y cómoda con una apariencia natural. Ofrece una cobertura media y construible, y cuenta con ingredientes protectores que ayudan a mantener la piel saludable. Con una calificación positiva y comentarios elogiosos de los usuarios, esta base puede ser una excelente opción para quienes deseen un maquillaje de alta calidad que cuide su piel y les permita expresar su estilo con confianza."
  },{
    id: 11,
    titulo: "Revlon 1875 W Secador de pelo turbo voluminizador",
    producto: "El Revlon 1875 W Secador de pelo turbo voluminizador es una potente herramienta de secado ",
    info: "El secador ofrece 3 posiciones de calor y 2 velocidades, lo que permite un secado y estilizado flexibles según las necesidades del usuario. Además, cuenta con un botón de flujo de aire del turbo para aumentar instantáneamente el caudal de aire y lograr un secado más rápido, así como un botón de aire frío para fijar el estilo.",
    img: "https://m.media-amazon.com/images/I/71u+Bigyy7L._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3QnmtYI",
    review: "El Revlon 1875 W Secador de pelo turbo voluminizador ha sido calificado con 4.6 estrellas sobre 5, basado en 17,101 calificaciones y 179 preguntas respondidas. Los usuarios elogian su potencia de 1875 vatios, que proporciona un secado rápido y efectivo. También destacan la función de aire frío para fijar el estilo y el accesorio difusor incluido, que ayuda a definir y dar volumen al cabello.",
    pro: "Potente motor de 1875 vatios\n- Triple revestimiento de cerámica horneada y cristales de turmalina\n- 3 posiciones de calor y 2 velocidades para un secado y estilizado flexibles\n- Botón de flujo de aire del turbo para secado más rápido\n- Botón de aire frío para fijar el estilo\n- Incluye accesorio difusor para definir y dar volumen al cabello",
    contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, el Revlon 1875 W Secador de pelo turbo voluminizador es una opción eficiente para quienes buscan un secador potente y versátil. Su combinación de revestimiento de cerámica y cristales de turmalina proporciona resultados de secado rápidos sin comprometer el brillo y la suavidad del cabello. Además, ofrece funciones de aire frío y difusor para estilizar y dar volumen al cabello. Con una alta calificación y comentarios positivos de los usuarios, este secador de pelo puede ser una excelente elección para cuidar y estilizar tu cabello."
  },{
    id: 10,
    titulo: "OKAY APRICOT - Exfoliante facial de 6 onzas / 6.00 oz",
    producto: "El OKAY APRICOT - Exfoliante facial es un exfoliante en forma de scrub diseñado especialmente para la piel propensa al acné.",
    info: "Este exfoliante facial es ideal para limpiar las imperfecciones y minimizar los poros, dejando la piel con una sensación fresca y renovada. No contiene alcohol, sulfatos ni parabenos, y ha sido fabricado en los Estados Unidos.",
    img: "https://m.media-amazon.com/images/I/51EH9qO7XXL._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3YpRv4a",
    review: "El OKAY APRICOT - Exfoliante facial ha sido calificado con 4.6 estrellas sobre 5, basado en 647 calificaciones y 7 preguntas respondidas. Los usuarios destacan su efectividad para evitar manchas y puntos negros, así como su capacidad para limpiar e hidratar la piel sin resecarla.",
    pro: "ontiene extracto de albaricoque natural y ácido salicílico\n- Incluye exfoliantes naturales de nogal\n- Ayuda a evitar manchas y puntos negros\n- Deja la piel recién limpia, hidratada y energizada\n- Minimiza los poros y ayuda a limpiar las imperfecciones",
    contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, el OKAY APRICOT - Exfoliante facial es una opción efectiva para aquellos con piel propensa al acné. Su fórmula con extracto de albaricoque y ácido salicílico ayuda a evitar manchas y puntos negros, mientras que los exfoliantes naturales de nogal limpian e hidratan la piel. Es un exfoliante suave que deja la piel fresca y energizada, sin resecarla. Si buscas un exfoliante facial para combatir el acné y mantener una piel limpia y saludable, este producto podría ser una excelente opción para ti."
  },{
    id: 9,
    titulo: "Real Techniques - Juego de brochas de maquillaje",
    producto: "El Real Techniques - Juego de brochas de maquillaje incluye una esponja de maquillaje número uno para una aplicación suave de la base.",
    info: "El juego contiene 5 piezas y está diseñado para su uso diario. Las brochas están hechas de aluminio y son adecuadas para todas las pieles. Incluye una esponja de maquillaje sin látex y varias brochas versátiles para aplicar blush y la fundación de manera profesional.",
    img: "https://m.media-amazon.com/images/I/61U76RevvIL._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3qn2gYr",
    review: "El Real Techniques - Juego de brochas de maquillaje tiene una calificación de 4.8 estrellas sobre 5, basada en 27,863 calificaciones y 17 preguntas respondidas. Los usuarios elogian la suavidad y la eficacia de la esponja de maquillaje, así como la calidad y versatilidad de las brochas incluidas en el juego.  Cuenta con un diseño revolucionario con tecnología de espuma sin látex, que permite mezclar uniformemente la base líquida para obtener un acabado suave y mejorado. Puede usarse en húmedo para lograr una luminosidad brillante o en seco para una cobertura completa. Además, el juego también incluye una variedad de brochas para lograr un aspecto aerógrafo y una aplicación impecable, como una brocha con borde plano para contornear alrededor de los ojos y la nariz, laterales redondos para mezclar áreas más grandes de la cara y una punta de precisión para cubrir defectos e imperfecciones",
    pro: "Esponja de maquillaje número uno para una aplicación suave de la base\n- Brochas de alta calidad para lograr un aspecto aerógrafo e impecable\n- Diseño revolucionario con tecnología de espuma sin látex\n- Uso en húmedo o en seco para diferentes acabados\n- Variedad de brochas para diferentes propósitos de maquillaje",
    contra: "No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, el Real Techniques - Juego de brochas de maquillaje es una excelente opción para lograr un maquillaje profesional y con acabado impecable. La esponja de maquillaje número uno y las brochas de alta calidad incluidas en el juego permiten una aplicación suave de la base y un aspecto aerógrafo. Es ideal para uso diario y es adecuado para diferentes tipos de piel. Si buscas un set de brochas versátil y de calidad, este juego podría ser una excelente elección para ti."
  }, {
    id: 8,
    titulo: "Colorescience Total Eye",
    producto: "La Colorescience Total Eye es una terapia de renovación antienvejecimiento 3 en 1 diseñada para reducir las arrugas y ojeras.",
    info: "Esta solución de maquillaje líquido se presenta en forma de cremas, geles y lociones. Está disponible en diferentes tonos, incluyendo Beige Bronceado, Deep, Fair y Mediano, para adaptarse a diversos tonos de piel. Es adecuada para personas con piel aceitosa, sensible, seca, normal o combinada.",
    img: "https://m.media-amazon.com/images/I/61vlY6JQFUL._SX522_.jpg",
    linkAfiliado: "https://amzn.to/3KpejLK",
    review: "La Colorescience Total Eye cuenta con una calificación de 4.3 estrellas sobre 5, basada en 2,200 calificaciones y 77 preguntas respondidas. Los usuarios destacan sus propiedades antienvejecimiento y su capacidad para proporcionar un aspecto descansado y juvenil alrededor de los ojos.",
    pro: " Terapia de renovación antienvejecimiento 3 en 1\n- Reduce arrugas y ojeras\n- Proporciona un aspecto descansado y juvenil\n- Contiene potentes ingredientes clínicos\n- Adecuada para diferentes tonos de piel",
    contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, la Colorescience Total Eye es una terapia de renovación antienvejecimiento completa para tratar las arrugas y ojeras alrededor de los ojos. Con su fórmula con potentes ingredientes clínicos, esta solución en maquillaje líquido ofrece un aspecto descansado y juvenil. Además, su disponibilidad en diferentes tonos la hace adecuada para diversos tonos de piel. Si buscas mejorar la apariencia de la piel alrededor de los ojos, esta terapia podría ser una opción a considerar."
  }, {
    id: 7,
    titulo: "ghd Platinum+ Styler",
    producto: "La ghd Platinum+ Styler es una plancha plana inteligente que utiliza tecnología predictiva para controlar el calor 250 veces por segundo.",
    info: "Esta herramienta profesional de peinado es adecuada para todo tipo de cabello. Su diseño en forma de barril y su tecnología avanzada hacen que el peinado sea más fácil y efectivo, garantizando resultados de calidad de salón desde la raíz hasta las puntas.",
    img: "https://m.media-amazon.com/images/I/61W6ELJKwlL._SX522_.jpg",
    linkAfiliado: "https://amzn.to/44UayWB",
    review: "La ghd Platinum+ Styler cuenta con una calificación de 4.4 estrellas sobre 5, basada en 2,318 calificaciones y 119 preguntas respondidas en Amazon. Los usuarios elogian sus resultados, brindando un cabello más fuerte, brillante y con una mejor protección del color.",
    pro: "Menos rotura y mayor protección del color\n- Apta para todo tipo de cabello\n- Diseño en forma de barril para peinados efectivos\n- Resultados de calidad de salón",
    contra: "No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, la ghd Platinum+ Styler es una plancha plana de alta calidad que utiliza tecnología avanzada para obtener resultados excepcionales en el peinado. Su capacidad de predecir las necesidades del cabello y ajustar el calor de manera óptima la convierte en una herramienta profesional ideal para lograr un cabello más fuerte, brillante y con protección del color. Si buscas una plancha alisadora de alto rendimiento, esta opción podría ser la adecuada para ti."
  }, {
    id: 6,
    titulo: "TruSkin - Suero de vitamina C para cara",
    producto: "El suero facial antienvejecimiento de TruSkin combina vitamina C con ácido hialurónico botánico, vitamina E, hamamelis de bruja.",
    info: "Este suero hidratante e iluminador es adecuado para varios usos, incluyendo para manos, rostro, piel y cuerpo. Es apto para todo tipo de pieles, incluyendo las sensibles, y se puede utilizar tanto de día como de noche. Su fórmula a base de plantas está libre de colores sintéticos, fragancias, parabenos, ftalatos, sulfatos, PEG u OMG, garantizando así una experiencia suave y sedosa en el cuidado de la piel.",
    img: "https://m.media-amazon.com/images/I/61eCRxzmRxL._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3Kv6qEB",
    review: "El suero de vitamina C de TruSkin tiene una calificación de 4.3 estrellas sobre 5, basada en 141,619 calificaciones y 608 preguntas respondidas en Amazon. Los clientes reales elogian los resultados de una piel más brillante y fresca después de usar este suero antienvejecimiento.",
    pro: "Ventajas del suero facial de vitamina C de TruSkin:\n- Efecto antienvejecimiento e iluminador para la piel\n- Apto para todo tipo de pieles, incluyendo sensibles\n- Fórmula a base de plantas y libre de químicos dañinos\n- Certificado libre de crueldad animal por Leaping Bunny\n- Garantía de satisfacción de 90 días",
    contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, el suero de vitamina C de TruSkin es un poderoso aliado en el cuidado de la piel, proporcionando beneficios antienvejecimiento e iluminadores. Su fórmula natural y suave lo hace apto para todo tipo de pieles, y su garantía de satisfacción de 90 días brinda confianza a los usuarios para probarlo. Si buscas mejorar la apariencia de arrugas y manchas oscuras, este suero puede ser una excelente opción para incluir en tu rutina de cuidado facial."
  }, {
    id: 5,
    titulo: "FOREO LUNA 3 Cepillo de limpieza facial",
    producto: "El FOREO LUNA 3 es un cepillo de limpieza facial que ofrece una experiencia de nivel de spa en la comodidad de tu hogar.",
    info: "El LUNA 3 también funciona como masajeador facial antienvejecimiento. Sincronizado con la aplicación FOREO, ofrece una variedad de masajes reafirmantes y permite controlar la intensidad de las pulsaciones T-Sonic. Cada rutina de masaje se enfoca en áreas específicas para reducir arrugas y flacidez, y mejorar la absorción de los productos para el cuidado de la piel facial.",
    img: "https://m.media-amazon.com/images/I/71k3vyEeBTL._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3OJSA3z",
    review: "El cepillo de limpieza facial FOREO LUNA 3 tiene una calificación de 4.3 estrellas sobre 5, basada en 1,013 calificaciones. Los usuarios mencionan que es altamente efectivo para limpiar la piel sin irritarla. Además, destacan su función de masajeador facial y cómo mejora la absorción de los productos para el cuidado de la piel.",
    pro: "Limpieza facial de nivel de spa\n- Masajes reafirmantes personalizables\n- Silicona ultra higiénica\n- Impermeable, se puede usar en la ducha\n- Garantía de 2 años contra defectos\n- Mejora la absorción de productos para el cuidado de la piel",
    contra: "No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, el FOREO LUNA 3 es un cepillo de limpieza facial y masajeador antienvejecimiento que ofrece una experiencia de spa en casa. Con su silicona ultra higiénica, es seguro para el cuerpo y mejora la apariencia de la piel al limpiarla y aumentar la absorción de productos para el cuidado facial. Su diseño impermeable permite su uso en la ducha para una rutina de cuidado facial simple y fácil."
  }, {
    id: 4,
    titulo: "NYX PROFESSIONAL MAKEUP - Crema labial mate suave",
    producto: "NYX PROFESSIONAL MAKEUP ofrece una crema labial mate suave que proporciona una alta pigmentación en los labios.",
    info: "La crema labial mate ofrece colores intensos y duraderos, manteniendo los labios hidratados y coloridos durante horas. Es adecuada para todo tipo de pieles y proporciona un acabado mate sin resecar los labios.",
    img: "https://m.media-amazon.com/images/I/61QeBhYd29S._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3s2n0Fl",
    review: "La crema labial mate de NYX PROFESSIONAL MAKEUP tiene una calificación de 4.3 estrellas sobre 5, basada en 39,003 calificaciones. Los usuarios mencionan que esta crema labial ofrece un acabado mate suave y colores intensos que duran mucho tiempo. Les gusta cómo mantiAlta pigmentación\n- Fórmula suave y sedosa\n- Acabado mate duradero\n- Mantiene los labios hidratados\n- Variedad de colores disponibles",
    contra: "No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, la crema labial mate suave de NYX PROFESSIONAL MAKEUP es una opción ideal para aquellos que buscan colores intensos y un acabado mate duradero sin sacrificar la hidratación de los labios. Con una amplia gama de colores disponibles, esta crema labial ofrece una fórmula suave y sedosa que se mantendrá intacta por horas."
  }, {
    id: 3,
    titulo: "Naked Cosmetics TRÍO RÚSTICO URBANO PRESIONADO PALETA DE SOMBRAS DE OJOS",
    producto: "La paleta de sombras de ojos Urban Rustic de Naked Cosmetics es un trío de sombras de ojos prensadas altamente pigmentadas. ",
    info: "Las sombras de ojos prensadas en la paleta Urban Rustic ofrecen una gama de tonos rústicos para crear diversos looks. Son perfectas para viajar debido a su tamaño compacto. Los pigmentos son de alta calidad y proporcionan un color intenso. La paleta incluye una clave de color para identificar el equivalente de polvo suelto de cada sombra.",
    img: "https://m.media-amazon.com/images/I/61eRaM3XjyL._SX466_.jpg",
    linkAfiliado: "https://amzn.to/3QwiYiD",
    review: "La paleta de sombras de ojos Urban Rustic de Naked Cosmetics tiene una calificación de 4.6 estrellas sobre 5, basada en 3 calificaciones. Los usuarios mencionan que las sombras son altamente pigmentadas y fáciles de aplicar. Les gusta la variedad de tonos rústicos y el acabado suave y sedoso. Los fanáticos de los pigmentos de la marca están satisfechos con esta paleta compacta que ofrece la misma calidad en sombras prensadas.",
    pro: "Ventajas de la paleta de sombras de ojos Urban Rustic de Naked Cosmetics:\n- Sombras prensadas altamente pigmentadas\n- Variedad de tonos rústicos\n- Acabado suave y sedoso\n- Tamaño de viaje, ideal para llevar\n- Pigmentos de alta calidad",
    contra: "Desventajas del producto:\n- No se mencionan desventajas en las calificaciones proporcionadas.",
    resumen: "En resumen, la paleta de sombras de ojos Urban Rustic de Naked Cosmetics es un trío de sombras prensadas altamente pigmentadas que ofrece una variedad de tonos rústicos. Con 12 años de experiencia en fabricación de pigmentos, la marca proporciona la misma calidad y recompensa de alto color en esta paleta compacta, perfecta para viajar y lograr looks intensos y sedosos."
  },{
    id: 2,
    titulo: "Neutrogena - Hidratante facial Hydro Boost con ácido hialurónico y protector solar SPF 50 de amplio espectro",
    producto: "El hidratante facial Hydro Boost de Neutrogena es un gel de agua con ácido hialurónico y un SPF 50 de amplio espectro.",
    info: "Este hidratante facial contiene Helioplex, un protector solar de amplio espectro con SPF 50 que protege contra la radiación UVA y UVB. Es adecuado para todos los tonos de piel y se absorbe rápidamente, proporcionando una piel más radiante y saludable en solo 1 semana. Su fórmula también incluye ácido hialurónico hidratante, glicerina para una hidratación profunda y antioxidantes supercargados, incluida la vitamina E, para proteger contra los agresores ambientales diarios.",
    img: "https://m.media-amazon.com/images/I/71SmBhXzwnL._AC_SX679_.jpg",
    linkAfiliado: "https://amzn.to/3ONdleU",
    review: "El hidratante facial Hydro Boost de Neutrogena tiene una calificación de 4.4 estrellas sobre 5, basada en 4,851 calificaciones y ha respondido 28 preguntas de los clientes. Muchos usuarios destacan su capacidad para hidratar y calmar la piel seca, así como su protección solar SPF 50 de amplio espectro. Algunos mencionan que es de rápida absorción y no deja la piel grasa. Sin embargo, algunos usuarios con pieles muy sensibles mencionan que prefieren una versión sin fragancia.",
    pro: "Ventajas del hidratante facial Hydro Boost de Neutrogena:\n- Hidratación duradera y calma la piel seca\n- Protección solar SPF 50 de amplio espectro (Helioplex)\n- Rápida absorción y no graso\n- Contiene ácido hialurónico hidratante y antioxidantes\n- No contiene aceites, parabenos, oxibenzona ni colorantes\n- Recomendado por dermatólogos",
    contra: "Desventajas del producto:\n- Puede no ser adecuado para usuarios con piel muy sensible que prefieren productos sin fragancia",
    resumen: "En resumen, el hidratante facial Hydro Boost de Neutrogena es un gel de agua con SPF 50 de amplio espectro, formulado con ácido hialurónico y antioxidantes para hidratar y calmar la piel seca. Su protección solar y rápida absorción lo hacen ideal para uso diario. Sin embargo, si tienes piel muy sensible, es posible que prefieras una versión sin fragancia."
  }, {
    id: 1,
    titulo: "L'Oreal Paris - Máscara telescópica impermeable para levantamiento de ojos, alargamiento y voluminización",
    producto: "La máscara telescópica impermeable de L'Oreal Paris proporciona un levantamiento instantáneo de pestañas",
    info: "Esta máscara de ojos fácil de aplicar está disponible en color negro (black Waterproof) y es adecuada para ojos sensibles, ya que ha sido probada por oftalmólogos. Se puede retirar fácilmente con agua y jabón. Para obtener los mejores resultados de maquillaje, se recomienda seguir dos pasos: primero, levantar y cargar las pestañas con las cerdas de gancho frontal para alargar y dar volumen de raíz a punta, y luego utilizar el peine de gancho lateral para separar las pestañas.",
    img: "https://m.media-amazon.com/images/I/61Hb9G-3IqL._SX466_.jpg",
    linkAfiliado: "https://amzn.to/43ZP49s",
    review: "La máscara telescópica de L'Oreal Paris tiene una calificación de 4.1 estrellas sobre 5, basada en 3,834 calificaciones y ha respondido 3 preguntas de los clientes. Muchos usuarios destacan su efecto de levantamiento instantáneo y la durabilidad del producto durante largos períodos de tiempo. Sin embargo, algunos mencionan que puede requerir más de una capa para obtener un aspecto más dramático.",
    pro: "Ventajas de la máscara telescópica de L'Oreal Paris:\n- Levantamiento instantáneo de pestañas, volumen y longitud visible\n- Resistente al agua, ideal para uso prolongado\n- Adecuada para ojos sensibles, probada por oftalmólogos\n- Fácil de aplicar con un cepillo de cerdas de doble gancho\n- Disponible en color negro",
    contra: "Desventajas del producto:\n- Puede requerir más de una capa para un aspecto más dramático",
    resumen: "En resumen, la máscara telescópica impermeable de L'Oreal Paris es una opción versátil para realzar el aspecto de las pestañas con un levantamiento instantáneo, volumen y longitud visible. Su resistencia al agua y durabilidad de hasta 36 horas la hacen adecuada para un uso prolongado. Es una opción recomendada para aquellos que buscan una máscara de pestañas de alta calidad y fácil de aplicar para realzar su mirada."
  }
]